quotation/urls.py
from django.urls import path
from . import ajax
from . import views

urlpatterns = [
    path('company/', views.comp_list, name="Comp_Index"),
    path('company/add/', views.comp_add, name="Comp_Add"),
    path('company/<int:comp_id>/', views.comp_detail, name="Comp_Detail"),
    path('company/<int:comp_id>/update/', views.comp_update, name="Comp_Update"),
    path('company/<int:comp_id>/tmpdel/', views.comp_tmpdel, name="Comp_TmpDel"),
    path('company/<int:comp_id>/permdel/', views.comp_permdel, name="Comp_PermDel"),
    path('item/', views.item_list, name="Item_Lsit"),
    path('item/add/', views.item_add, name="Item_add"),
    path('item/<int:item_id>/', views.item_detail, name="Item_Detail"),
    path('item/<int:item_id>/export/', views.item_hstr_export, name="Item_Hist_Exprt"),
    path('item/<int:item_id>/update/', views.item_update, name="Item_Update"),
    path('item/<int:item_id>/permdel/', views.item_permdel, name="Item_PermDel"),
    path('item/cate/', views.cate_list, name="Cate_Lsit"),
    path('item/cate/<cate_id>/delete/', views.cate_del, name="Cate_Del"),
    path('item/cate/<cate_id>/prmntdel/', views.cate_prmntdel, name="Cate_PrmntDel"),
    path('item/mfg/', views.mfg_list, name="MFG_Lsit"),
    path('item/mfg/<mfg_id>/delete/', views.mfg_del, name="MFG_Del"),
    path('item/mfg/<mfg_id>/prmntdel/', views.mfg_prmntdel, name="MFG_PrmntDel"),
    path('inquiry/', views.inquiry_list, name="Inquiry_List"),
    path('inquiry/add/', views.inquiry_add, name="Inquiry_Add"),
    path('inquiry/<int:inqry_id>/', views.inquiry_detail, name="Inquiry_Detail"),
    path('inquiry/<int:inqry_id>/addnewquota/', views.quota_newadd, name="Quota_Add"),
    path('inquiry/<int:inqry_id>/close/', views.inquiry_close, name="Inquiry_Close"),
    path('inquiry/<int:inqry_id>/del/', views.inquiry_del, name="Inquiry_Del"),
    path('inquiry/<int:inqry_id>/exportxls/', views.inquiry_export, name="Inquiry_Eptxls"),
    path('inquiry/<int:inqry_id>/importxls/', views.inqry_imprtres, name="Inquiry_Imptxls"),
    path('quota/<int:quota_id>/', views.quota_inpageupdate, name="Quota_Inpgupdate"),
    path('quota/<int:quota_id>/delete/', views.quota_del, name="Quota_Del"),
    path('ajax/itemdetail/', ajax.getdetail, name="Ajax_Getitem"),
    path('ajax/mfglist/', ajax.get_mfg, name="Ajax_GetMFG"),
    path('ajax/mfgcode/', ajax.get_mfgcode, name="Ajax_GetMFGCode"),
]

quotation/models.py
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

# Create your models here.


class ModelBase(models.Model):
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)
    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True


class Company(ModelBase):
    sn = models.CharField(max_length=10, unique=True)
    fullname = models.CharField(max_length=50)
    shortname = models.CharField(max_length=20)
    spnsr = models.CharField(max_length=20)
    spnsr_shrtname = models.CharField(max_length=20, blank=True, null=True)
    tel = models.CharField(max_length=20)
    tel_ext = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    remark = models.CharField(max_length=300, blank=True, null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='companies',
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.shortname, self.spnsr)


class Category(models.Model):
    sn = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=20)
    history = HistoricalRecords()
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return "{}_{}".format(self.sn, self.name)


class Manufacturer(ModelBase):
    sn = models.CharField(max_length=4, unique=True)
    name = models.CharField(max_length=50)
    fullname = models.CharField(max_length=50, null=True, blank=True)
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='manufacturer',
        limit_choices_to={'is_open': True},
    )
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return "{}_{}".format(self.sn, self.name)


class Item(ModelBase):
    sn = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='items',
        limit_choices_to={'is_open': True},
    )
    mfg = models.ForeignKey(
        Manufacturer,
        on_delete=models.PROTECT,
        related_name='items',
        limit_choices_to={'is_open': True},
    )
    specmain = models.CharField(max_length=100)
    remark = models.CharField(max_length=250, blank=True, null=True)
    is_inquiry = models.BooleanField(default=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='items',
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.cate.name, self.name)

    def last_quotatime(self):
        last_quota = self.itemquota.all().order_by("-qdate").first()
        if last_quota:
            if last_quota.qdate:
                return last_quota.qdate.strftime("%Y-%m-%d")
            else:
                return None
        else:
            return None


class Inquiry(ModelBase):

    class Status(models.TextChoices):
        ONGOING = '詢價中'
        END = '結案'

    sn = models.CharField(max_length=12)
    startdate = models.DateField()
    enddate = models.DateField()
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='inquirys',
    )
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='inquirys',
        limit_choices_to={'is_open': True},
    )
    company = models.ForeignKey(
        Company,
        on_delete=models.PROTECT,
        related_name='inquirys',
        limit_choices_to={'is_open': True},
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.ONGOING,
    )
    remark = models.CharField(
        max_length=300,
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.cate.name, self.company.shortname)

    def last_quotatime(self):
        last_itemquota = self.itemquota.all().order_by("-qdate").first()
        if last_itemquota:
            if last_itemquota.qdate:
                return last_itemquota.qdate.strftime("%Y-%m-%d")
            else:
                return None
        else:
            return None
        # if self.itemquota.all().order_by("-qdate").first().qdate:
        #     return self.itemquota.all().order_by("-qdate").first().qdate.strftime("%Y-%m-%d")
        # else:
        #     return None


class Current(models.Model):
    code = models.CharField(max_length=4)
    name = models.CharField(max_length=10)
    history = HistoricalRecords()

    def __str__(self):
        return self.name


class ItemQuota(ModelBase):
    itemsn = models.ForeignKey(
        Item,
        on_delete=models.PROTECT,
        related_name='itemquota',
    )
    inquirysn = models.ForeignKey(
        Inquiry,
        on_delete=models.PROTECT,
        related_name='itemquota',
    )
    count = models.IntegerField(default=1)
    price = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        blank=True,
        null=True,
    )
    crnt = models.ForeignKey(
        Current,
        on_delete=models.PROTECT,
        related_name='itemquota',
        blank=True,
        null=True,
    )
    xchgrt = models.DecimalField(
        max_digits=12,
        decimal_places=6,
        blank=True,
        null=True,
    )
    is_new = models.BooleanField(default=False)
    qdate = models.DateField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}_{}".format(self.inquirysn.sn, self.itemsn.name)

    def ntd_price(self):
        if self.price and self.xchgrt:
            return self.price * self.xchgrt
        else:
            return None

templates/quotation/inquiry/quota/inpgupdate.html
{% extends 'frame/nonavbase.html' %}

{% block title %}Inaenergy{% endblock %}
{% block content %}
  <section id="title">
    <div class="container">
      <div class="row">
        <div class="col-12">
            <h1 class="my-3">更新報價</h1>
        </div>
        <div class="col-12 my-3">
          <div class="text-right"><small>新增日期：{{ quota.addtime|date:"Y-m-d h:i:s a" }} by {{ quota.history.first.history_user }}</small></div>
          <div class="text-right"><small>上次修改日期：{{ quota.history.latest.history_date|date:"Y-m-d h:i:s a" }} by {{ quota.history.latest.history_user }}</small></div>
        </div>
      </div>
    </div>
  </section>

  <section id="quota">
    <div class="container">
      <div class="row">
        <div class="col-3">料號：</div>
        <div class="col-9 font-weight-bold">{{ quota.itemsn.sn }}</div>
        <div class="col-3">品項：</div>
        <div class="col-9 font-weight-bold">{{ quota.itemsn.name }}</div>
        <div class="col-3">類別：</div>
        <div class="col-9 font-weight-bold">{{ quota.itemsn.cate }}</div>
        <div class="col-3">廠商：</div>
        <div class="col-9 font-weight-bold">{{ quota.itemsn.mfg }}</div>
        <div class="col-3">規格：</div>
        <div class="col-9 font-weight-bold">{{ quota.itemsn.specmain }}</div>

      </div>
      <form method="POST" class="needs-validation" onsubmit="" novalidate>
        <div class="form-row">
          {% csrf_token %}
          <div class="col-9">
            <div class="form-group">
              <label for="id_{{ form.price.name }}">金額：</label>
              {{ form.price }}
              <div class="invalid-feedback">
                請輸入金額！
              </div>
            </div>
          </div>
          <div class="col-3">
            <div class="form-group">
              <label for="id_{{ form.crnt.name }}">幣別：</label>
              {{ form.crnt }}
              <div class="invalid-feedback">
                請選擇幣別！
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <label for="id_{{ form.qdate.name }}">日期：</label>
              {{ form.qdate }}
              <div class="invalid-feedback">
                請選擇日期！
              </div>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">送出</button>
        </div>
      </form>
    </div>
  </section>
  <script>
      window.onbeforeunload = function () {
          window.opener.location.reload();
      };
      $(document).ready(function() {
          $('#id_price, #id_crnt, #id_qdate').prop('required', true);
      });
  </script>
{% endblock %}

templates/quotation/inquiry/quota/newadd.html
{% extends 'frame/nonavbase.html' %}

{% block title %}Inaenergy{% endblock %}
{% block content %}
  <section id="title">
    <div class="container">
      <div class="row">
        <div class="col-12">
            <h1 class="my-5">新品項報價</h1>
        </div>
      </div>
    </div>
  </section>

  <section id="quota">
    <div class="container">
      <form method="POST" class="needs-validation" onsubmit="" novalidate>
        <div class="form-row">
          {% csrf_token %}
          <div class="col-12">
            <div class="form-group">
              <label for="id_{{ form.cate.name }}">*類別：</label>
              {{ form.cate }}
              <div class="invalid-feedback">
                請選擇類別！
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <label for="id_{{ form.mfg.name }}">*廠商：</label>
              {{ form.mfg }}
              <div class="invalid-feedback">
                請選擇廠商！
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <label for="id_{{ form.specmain.name }}">*規格：</label>
              {{ form.specmain }}
              <div class="invalid-feedback">
                請輸入規格！
              </div>
              <small id="nameHelpBlock" class="form-text text-muted">
                輸入主規格。
              </small>
            </div>
          </div>
          <div class="col-12 col-md-6">
            <div class="form-group">
              <label for="id_{{ form.name.name }}">*品項名稱：</label>
              {{ form.name }}
              <div class="invalid-feedback">
                請輸入品項名稱！
              </div>
              <small id="fullnameHelpBlock" class="form-text text-muted">
                輸入品項完整名稱。
              </small>
            </div>
          </div>
          <div class="col-9">
            <div class="form-group">
              <label for="id_{{ qryform.price.name }}">金額：</label>
              {{ qryform.price }}
              <div class="invalid-feedback">
                請輸入金額！
              </div>
            </div>
          </div>
          <div class="col-3">
            <div class="form-group">
              <label for="id_{{ qryform.crnt.name }}">幣別：</label>
              {{ qryform.crnt }}
              <div class="invalid-feedback">
                請選擇幣別！
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <label for="id_{{ qryform.qdate.name }}">日期：</label>
              {{ qryform.qdate }}
              <div class="invalid-feedback">
                請選擇日期！
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="form-group">
              <label for="id_{{ form.remark.name }}">備註：</label>
              {{ form.remark }}
              <div class="invalid-feedback">
                {{ form.remark.errors }}
              </div>
            </div>
          </div>
          <input type="hidden" name="author" value="{{ request.user.id }}">
          <div class="col-12">
            <button type="submit" class="btn btn-primary" id="submit">送出</button>
          </div>
        </div>
      </form>
    </div>
  </section>
  <script>
      window.onbeforeunload = function () {
          window.opener.location.reload();
      };
      $(document).ready(function() {
          $('#id_cate').prop('disabled', true);
          $('#id_price, #id_crnt, #id_qdate').prop('required', true);
          let cate_id = $('#id_cate :selected').val();
          $.ajax({
              url: '/quotation/ajax/mfglist/',
              method: "GET",
              data: {
                  cate_id: cate_id,
              },
              success: function (res){
                  $('#id_mfg').empty();
                  $("#id_mfg").append($("<option value>").text("---------"));
                  for (const i in res.mfgs){
                      let option = $("<option>").val(res.mfgs[i].id).text(res.mfgs[i].id_name);
                      $("#id_mfg").append(option);
                  }
              },
          });
          $(document).on('click', '#submit', function () {
            $('select').prop('disabled', false);
        });
      });
  </script>
{% endblock %}