quotation/urls.py
from django.urls import path
from . import ajax
from . import views

urlpatterns = [
    path('company/', views.comp_list, name="Comp_Index"),
    path('company/add/', views.comp_add, name="Comp_Add"),
    path('company/<int:comp_id>/', views.comp_detail, name="Comp_Detail"),
    path('company/<int:comp_id>/update/', views.comp_update, name="Comp_Update"),
    path('company/<int:comp_id>/tmpdel/', views.comp_tmpdel, name="Comp_TmpDel"),
    path('company/<int:comp_id>/permdel/', views.comp_permdel, name="Comp_PermDel"),
    path('item/', views.item_list, name="Item_Lsit"),
    path('item/add/', views.item_add, name="Item_add"),
    path('item/<int:item_id>/', views.item_detail, name="Item_Detail"),
    path('item/<int:item_id>/export/', views.item_hstr_export, name="Item_Hist_Exprt"),
    path('item/<int:item_id>/update/', views.item_update, name="Item_Update"),
    path('item/<int:item_id>/permdel/', views.item_permdel, name="Item_PermDel"),
    path('item/cate/', views.cate_list, name="Cate_Lsit"),
    path('item/cate/<cate_id>/delete/', views.cate_del, name="Cate_Del"),
    path('item/cate/<cate_id>/prmntdel/', views.cate_prmntdel, name="Cate_PrmntDel"),
    path('item/mfg/', views.mfg_list, name="MFG_Lsit"),
    path('item/mfg/<mfg_id>/delete/', views.mfg_del, name="MFG_Del"),
    path('item/mfg/<mfg_id>/prmntdel/', views.mfg_prmntdel, name="MFG_PrmntDel"),
    path('inquiry/', views.inquiry_list, name="Inquiry_List"),
    path('inquiry/add/', views.inquiry_add, name="Inquiry_Add"),
    path('inquiry/<int:inqry_id>/', views.inquiry_detail, name="Inquiry_Detail"),
    path('inquiry/<int:inqry_id>/addnewquota/', views.quota_newadd, name="Quota_Add"),
    path('inquiry/<int:inqry_id>/close/', views.inquiry_close, name="Inquiry_Close"),
    path('inquiry/<int:inqry_id>/del/', views.inquiry_del, name="Inquiry_Del"),
    path('inquiry/<int:inqry_id>/exportxls/', views.inquiry_export, name="Inquiry_Eptxls"),
    path('inquiry/<int:inqry_id>/importxls/', views.inqry_imprtres, name="Inquiry_Imptxls"),
    path('quota/<int:quota_id>/', views.quota_inpageupdate, name="Quota_Inpgupdate"),
    path('quota/<int:quota_id>/delete/', views.quota_del, name="Quota_Del"),
    path('ajax/itemdetail/', ajax.getdetail, name="Ajax_Getitem"),
    path('ajax/mfglist/', ajax.get_mfg, name="Ajax_GetMFG"),
    path('ajax/mfgcode/', ajax.get_mfgcode, name="Ajax_GetMFGCode"),
]

quotation/models.py
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

# Create your models here.


class ModelBase(models.Model):
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)
    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True


class Company(ModelBase):
    sn = models.CharField(max_length=10, unique=True)
    fullname = models.CharField(max_length=50)
    shortname = models.CharField(max_length=20)
    spnsr = models.CharField(max_length=20)
    spnsr_shrtname = models.CharField(max_length=20, blank=True, null=True)
    tel = models.CharField(max_length=20)
    tel_ext = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    remark = models.CharField(max_length=300, blank=True, null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='companies',
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.shortname, self.spnsr)


class Category(models.Model):
    sn = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=20)
    history = HistoricalRecords()
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return "{}_{}".format(self.sn, self.name)


class Manufacturer(ModelBase):
    sn = models.CharField(max_length=4, unique=True)
    name = models.CharField(max_length=50)
    fullname = models.CharField(max_length=50, null=True, blank=True)
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='manufacturer',
        limit_choices_to={'is_open': True},
    )
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return "{}_{}".format(self.sn, self.name)


class Item(ModelBase):
    sn = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='items',
        limit_choices_to={'is_open': True},
    )
    mfg = models.ForeignKey(
        Manufacturer,
        on_delete=models.PROTECT,
        related_name='items',
        limit_choices_to={'is_open': True},
    )
    specmain = models.CharField(max_length=100)
    remark = models.CharField(max_length=250, blank=True, null=True)
    is_inquiry = models.BooleanField(default=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='items',
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.cate.name, self.name)

    def last_quotatime(self):
        last_quota = self.itemquota.all().order_by("-qdate").first()
        if last_quota:
            if last_quota.qdate:
                return last_quota.qdate.strftime("%Y-%m-%d")
            else:
                return None
        else:
            return None


class Inquiry(ModelBase):

    class Status(models.TextChoices):
        ONGOING = '詢價中'
        END = '結案'

    sn = models.CharField(max_length=12)
    startdate = models.DateField()
    enddate = models.DateField()
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='inquirys',
    )
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='inquirys',
        limit_choices_to={'is_open': True},
    )
    company = models.ForeignKey(
        Company,
        on_delete=models.PROTECT,
        related_name='inquirys',
        limit_choices_to={'is_open': True},
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.ONGOING,
    )
    remark = models.CharField(
        max_length=300,
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.cate.name, self.company.shortname)

    def last_quotatime(self):
        last_itemquota = self.itemquota.all().order_by("-qdate").first()
        if last_itemquota:
            if last_itemquota.qdate:
                return last_itemquota.qdate.strftime("%Y-%m-%d")
            else:
                return None
        else:
            return None
        # if self.itemquota.all().order_by("-qdate").first().qdate:
        #     return self.itemquota.all().order_by("-qdate").first().qdate.strftime("%Y-%m-%d")
        # else:
        #     return None


class Current(models.Model):
    code = models.CharField(max_length=4)
    name = models.CharField(max_length=10)
    history = HistoricalRecords()

    def __str__(self):
        return self.name


class ItemQuota(ModelBase):
    itemsn = models.ForeignKey(
        Item,
        on_delete=models.PROTECT,
        related_name='itemquota',
    )
    inquirysn = models.ForeignKey(
        Inquiry,
        on_delete=models.PROTECT,
        related_name='itemquota',
    )
    count = models.IntegerField(default=1)
    price = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        blank=True,
        null=True,
    )
    crnt = models.ForeignKey(
        Current,
        on_delete=models.PROTECT,
        related_name='itemquota',
        blank=True,
        null=True,
    )
    xchgrt = models.DecimalField(
        max_digits=12,
        decimal_places=6,
        blank=True,
        null=True,
    )
    is_new = models.BooleanField(default=False)
    qdate = models.DateField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}_{}".format(self.inquirysn.sn, self.itemsn.name)

    def ntd_price(self):
        if self.price and self.xchgrt:
            return self.price * self.xchgrt
        else:
            return None

templates/quotation/item/manufacturer/list.html
{% extends 'frame/base.html' %}

{% block title %}廠商一覽 - 寶晶供應鏈管理系統{% endblock %}
{% block css %}
  <link href="/static/custom/page.css" rel="stylesheet">
{% endblock %}
{% block scripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
    <script>
      var options = {
        valueNames: [ 'cnt', 'cate', 'sn', 'name', 'fullname'],
        page: 10,
        pagination: [{
            name: "pagination",
            paginationClass: "pagination",
            innerWindow: 1,
            outerWindow: 1,
        }],
      };

      /*table = id of the div */
      var userList = new List('table', options);

      $('#editModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) // Button that triggered the modal
        var id = button.data('id')
        var sn = button.data('sn')
        var name = button.data('name')
        var fullname = button.data('fullname')  // Extract info from data-* attributes
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this)
        modal.find('.modal-title').text('更新廠商(' + sn + ')名稱:')
        modal.find('.model-body')
        modal.find('.modal-body input[id="id_mfg_id"]').val(id)
        modal.find('.modal-body input[id="id_name"]').val(name)
        modal.find('.modal-body input[id="id_fullname"]').val(fullname)
      });

      $('.delModal').on('click', function () {
          let mfg_id = $(this).data('id');
          let mfg_name = $(this).parent().parent().find('.name').text()
          var del = window.confirm('確定是否要刪除 "' + mfg_name +'" ?');
          if (del===true){
              window.location.href="/quotation/item/mfg/" + mfg_id+ "/delete/";
          }else{
              window.location.href="./";
          }
      });

      $('.delFvrModal').on('click', function () {
          let mfg_id = $(this).data('id');
          let mfg_name = $(this).parent().parent().find('.catename').text()
          var del = window.confirm('確定是否要永久刪除 "' + mfg_name +'" ?\r\n(從資料庫刪除，且不能再復原。)');
          if (del===true){
              window.location.href="/quotation/item/mfg/" + mfg_id+ "/prmntdel/";
          }else{
              window.location.href="./";
          }
      })
    </script>
{% endblock %}
{% block content %}
  <section id="doclist" class="py-3">
    <div class="container py-3">
      <h1 class="my-3">廠商一覽</h1>
      <a class="btn btn-secondary" href="{% url 'Item_Lsit' %}">返回品項列表</a>
      <div class="row">
        <div class="col-12 my-3">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
            新增
          </button>
          <!--彈出新增視窗-->
          <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">新增廠商</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form method="POST" class="needs-validation" onsubmit="" novalidate>
                  <div class="modal-body">
                    <div class="form-row">
                      {% csrf_token %}
                      <div class="col-6">
                        <div class="form-group">
                          <label for="id_{{ form.sn.name }}">*編號：</label>
                          {{ form.sn }}
                          <div class="invalid-feedback">
                            請輸入兩碼英文編號。
                          </div>
                        </div>
                      </div>
                      <div class="col-6">
                        <div class="form-group">
                          <label for="id_{{ form.cate.name }}">*類別：</label>
                          {{ form.cate }}
                          <div class="invalid-feedback">
                            請選擇類別。
                          </div>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-group">
                          <label for="id_{{ form.name.name }}">*名稱：</label>
                          {{ form.name }}
                          <div class="invalid-feedback">
                            請輸入名稱。
                          </div>
                        </div>
                      </div>
                      <div class="col-12">
                        <div class="form-group">
                          <label for="id_{{ form.fullname.name }}">完整名稱：</label>
                          {{ form.fullname }}
                          <div class="invalid-feedback">
                            請輸入名稱。
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                  <button type="submit" class="btn btn-primary">送出</button>
                </div>
                </form>
              </div>
            </div>
          </div>

          <!--彈出更新視窗-->
          <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="editModalLabel">編輯廠商名稱</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form method="POST" onsubmit="">
                  {% csrf_token %}
                  <div class="modal-body">
                      {{ updateform.mfg_id }}
                      <div class="form-group">
                        <label for="id_name" class="col-form-label">名稱:</label>
                        {{ updateform.name }}
                      </div>
                      <div class="form-group">
                        <label for="id_fullname" class="col-form-label">完整名稱:</label>
                        {{ updateform.fullname }}
                      </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">關閉</button>
                    <button type="submit" class="btn btn-primary">儲存</button>
                  </div>
                </form>
              </div>
            </div>
          </div>

        </div>
        <div class="col-lg-10">
          <div class="table-responsive" id="table">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col" class="sort fit" data-sort="cnt"></th>
                  <th scope="col" class="sort text-center fit" data-sort="cate">類別</th>
                  <th scope="col" class="sort text-center" data-sort="sn">編號</th>
                  <th scope="col" class="sort" data-sort="name">名稱</th>
                  <th scope="col" class="sort" data-sort="fullname">完整名稱</th>
                  <th scope="col">動作</th>
                </tr>
              </thead>
              <tbody class="list">
                {% for mfg in mfgs %}
                <tr>
                  <td class="cnt fit">{{ forloop.counter }}</td>
                  <td class="cate text-center">{{ mfg.cate }}</td>
                  <td class="sn text-center">{{ mfg.sn }}</td>
                  <td class="name">{{ mfg.name }}</td>
                  <td class="fullname">{{ mfg.fullname }}</td>
                  <td>
                    <button
                      type="button"
                      class="btn btn-sm btn-primary"
                      data-toggle="modal"
                      data-target="#editModal"
                      data-id="{{ mfg.id }}"
                      data-sn="{{ mfg.sn }}"
                      data-name="{{ mfg.name }}"
                      data-fullname="{{ mfg.fullname }}">編輯</button>
                    <button
                      type="button"
                      class="btn btn-sm btn-danger delModal"
                      data-id="{{ mfg.id }}">刪除</button>
                    {% if mfg.items.count == 0 %}
                      <button
                      type="button"
                      class="btn btn-sm btn-danger delFvrModal"
                      data-id="{{ mfg.id }}">永久刪除</button>
                    {% endif %}
                  </td>
                </tr>
                {% empty %}
                  <tr>
                    <td colspan="6" class="text-center"> 目前尚無任何品項。 </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <nav aria-label="Page navigation">
              <ul class="pagination"></ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}