quotation/urls.py
from django.urls import path
from . import ajax
from . import views

urlpatterns = [
    path('company/', views.comp_list, name="Comp_Index"),
    path('company/add/', views.comp_add, name="Comp_Add"),
    path('company/<int:comp_id>/', views.comp_detail, name="Comp_Detail"),
    path('company/<int:comp_id>/update/', views.comp_update, name="Comp_Update"),
    path('company/<int:comp_id>/tmpdel/', views.comp_tmpdel, name="Comp_TmpDel"),
    path('company/<int:comp_id>/permdel/', views.comp_permdel, name="Comp_PermDel"),
    path('item/', views.item_list, name="Item_Lsit"),
    path('item/add/', views.item_add, name="Item_add"),
    path('item/<int:item_id>/', views.item_detail, name="Item_Detail"),
    path('item/<int:item_id>/export/', views.item_hstr_export, name="Item_Hist_Exprt"),
    path('item/<int:item_id>/update/', views.item_update, name="Item_Update"),
    path('item/<int:item_id>/permdel/', views.item_permdel, name="Item_PermDel"),
    path('item/cate/', views.cate_list, name="Cate_Lsit"),
    path('item/cate/<cate_id>/delete/', views.cate_del, name="Cate_Del"),
    path('item/cate/<cate_id>/prmntdel/', views.cate_prmntdel, name="Cate_PrmntDel"),
    path('item/mfg/', views.mfg_list, name="MFG_Lsit"),
    path('item/mfg/<mfg_id>/delete/', views.mfg_del, name="MFG_Del"),
    path('item/mfg/<mfg_id>/prmntdel/', views.mfg_prmntdel, name="MFG_PrmntDel"),
    path('inquiry/', views.inquiry_list, name="Inquiry_List"),
    path('inquiry/add/', views.inquiry_add, name="Inquiry_Add"),
    path('inquiry/<int:inqry_id>/', views.inquiry_detail, name="Inquiry_Detail"),
    path('inquiry/<int:inqry_id>/addnewquota/', views.quota_newadd, name="Quota_Add"),
    path('inquiry/<int:inqry_id>/close/', views.inquiry_close, name="Inquiry_Close"),
    path('inquiry/<int:inqry_id>/del/', views.inquiry_del, name="Inquiry_Del"),
    path('inquiry/<int:inqry_id>/exportxls/', views.inquiry_export, name="Inquiry_Eptxls"),
    path('inquiry/<int:inqry_id>/importxls/', views.inqry_imprtres, name="Inquiry_Imptxls"),
    path('quota/<int:quota_id>/', views.quota_inpageupdate, name="Quota_Inpgupdate"),
    path('quota/<int:quota_id>/delete/', views.quota_del, name="Quota_Del"),
    path('ajax/itemdetail/', ajax.getdetail, name="Ajax_Getitem"),
    path('ajax/mfglist/', ajax.get_mfg, name="Ajax_GetMFG"),
    path('ajax/mfgcode/', ajax.get_mfgcode, name="Ajax_GetMFGCode"),
]

quotation/models.py
from django.db import models
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

# Create your models here.


class ModelBase(models.Model):
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)
    history = HistoricalRecords(inherit=True)

    class Meta:
        abstract = True


class Company(ModelBase):
    sn = models.CharField(max_length=10, unique=True)
    fullname = models.CharField(max_length=50)
    shortname = models.CharField(max_length=20)
    spnsr = models.CharField(max_length=20)
    spnsr_shrtname = models.CharField(max_length=20, blank=True, null=True)
    tel = models.CharField(max_length=20)
    tel_ext = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    remark = models.CharField(max_length=300, blank=True, null=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='companies',
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.shortname, self.spnsr)


class Category(models.Model):
    sn = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=20)
    history = HistoricalRecords()
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return "{}_{}".format(self.sn, self.name)


class Manufacturer(ModelBase):
    sn = models.CharField(max_length=4, unique=True)
    name = models.CharField(max_length=50)
    fullname = models.CharField(max_length=50, null=True, blank=True)
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='manufacturer',
        limit_choices_to={'is_open': True},
    )
    addtime = models.DateTimeField(auto_now_add=True)
    updatetime = models.DateTimeField(auto_now=True)
    is_open = models.BooleanField(default=True)

    def __str__(self):
        return "{}_{}".format(self.sn, self.name)


class Item(ModelBase):
    sn = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='items',
        limit_choices_to={'is_open': True},
    )
    mfg = models.ForeignKey(
        Manufacturer,
        on_delete=models.PROTECT,
        related_name='items',
        limit_choices_to={'is_open': True},
    )
    specmain = models.CharField(max_length=100)
    remark = models.CharField(max_length=250, blank=True, null=True)
    is_inquiry = models.BooleanField(default=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='items',
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.cate.name, self.name)

    def last_quotatime(self):
        last_quota = self.itemquota.all().order_by("-qdate").first()
        if last_quota:
            if last_quota.qdate:
                return last_quota.qdate.strftime("%Y-%m-%d")
            else:
                return None
        else:
            return None


class Inquiry(ModelBase):

    class Status(models.TextChoices):
        ONGOING = '詢價中'
        END = '結案'

    sn = models.CharField(max_length=12)
    startdate = models.DateField()
    enddate = models.DateField()
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='inquirys',
    )
    cate = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        related_name='inquirys',
        limit_choices_to={'is_open': True},
    )
    company = models.ForeignKey(
        Company,
        on_delete=models.PROTECT,
        related_name='inquirys',
        limit_choices_to={'is_open': True},
    )
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.ONGOING,
    )
    remark = models.CharField(
        max_length=300,
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}_{}_{}".format(self.sn, self.cate.name, self.company.shortname)

    def last_quotatime(self):
        last_itemquota = self.itemquota.all().order_by("-qdate").first()
        if last_itemquota:
            if last_itemquota.qdate:
                return last_itemquota.qdate.strftime("%Y-%m-%d")
            else:
                return None
        else:
            return None
        # if self.itemquota.all().order_by("-qdate").first().qdate:
        #     return self.itemquota.all().order_by("-qdate").first().qdate.strftime("%Y-%m-%d")
        # else:
        #     return None


class Current(models.Model):
    code = models.CharField(max_length=4)
    name = models.CharField(max_length=10)
    history = HistoricalRecords()

    def __str__(self):
        return self.name


class ItemQuota(ModelBase):
    itemsn = models.ForeignKey(
        Item,
        on_delete=models.PROTECT,
        related_name='itemquota',
    )
    inquirysn = models.ForeignKey(
        Inquiry,
        on_delete=models.PROTECT,
        related_name='itemquota',
    )
    count = models.IntegerField(default=1)
    price = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        blank=True,
        null=True,
    )
    crnt = models.ForeignKey(
        Current,
        on_delete=models.PROTECT,
        related_name='itemquota',
        blank=True,
        null=True,
    )
    xchgrt = models.DecimalField(
        max_digits=12,
        decimal_places=6,
        blank=True,
        null=True,
    )
    is_new = models.BooleanField(default=False)
    qdate = models.DateField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}_{}".format(self.inquirysn.sn, self.itemsn.name)

    def ntd_price(self):
        if self.price and self.xchgrt:
            return self.price * self.xchgrt
        else:
            return None

templates/quotation/item/add.html
{% extends 'frame/base.html' %}
{% block scripts %}
{% endblock %}
{% block title %}新增品項 - 寶晶供應鏈管理系統{% endblock %}
{% block content %}
  <section id="doclist" class="py-3">
    <div class="container py-3">
      <h1 class="my-3">新增品項</h1>
      <div class="row">
        <div class="col-12">
          <div id="msg" class="text-danger"></div>
          <div class="text-danger">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                  </div>
                {% endfor %}
              {% endfor %}
            {% endif %}
          </div>
        </div>
        <div class="col-12">
          <form method="POST" class="needs-validation" onsubmit="" novalidate>
            <div class="form-row">
              {% csrf_token %}
              <div class="col-12 my-2">{{ form.non_field_errors }}</div>
              <div class="col-12">
                <div class="row">
                  <div class="col-12 col-md-4">
                    <div class="form-group">
                      <label for="id_{{ form.cate.name }}">*類別：</label>
                      {{ form.cate }}
                      <div class="invalid-feedback">
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-4">
                    <div class="form-group">
                      <label for="id_{{ form.mfg.name }}">*廠商：</label>
                      {{ form.mfg }}
                      <div class="invalid-feedback">
                      </div>
                    </div>
                  </div>
                  <div class="col-6 col-md-4">
                    <div class="form-group">
                      <label for="id_{{ form.specmain.name }}">*規格編號：</label>
                      {{ form.specmain }}
                      <small id="nameHelpBlock" class="form-text text-muted">
                        輸入主規格。
                      </small>
                      <div class="invalid-feedback">
                        {{ form.specmain.errors }}
                      </div>
                    </div>
                  </div>
                  <div class="col-12 col-md-12">
                    <div class="form-group">
                      <label for="id_{{ form.name.name }}">*品項名稱：</label>
                      {{ form.name }}
                      <small id="fullnameHelpBlock" class="form-text text-muted">
                        輸入品項完整名稱。
                      </small>
                      <div class="invalid-feedback">
                        {{ form.name.errors }}
                      </div>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <label for="id_{{ form.remark.name }}">備註：</label>
                      {{ form.remark }}
                      <div class="invalid-feedback">
                        {{ form.remark.errors }}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <input type="hidden" name="author" value="{{ request.user.id }}">
              <div class="col-12">
                <a role="button" class="btn btn-danger" href="{% url 'Item_Lsit' %}">取消</a>
                <button type="submit" class="btn btn-primary" id="submit">送出</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <script>
    $(document).ready(function() {
        $(document).on('change', '#id_cate', function (){
            let cate_id = $('#id_cate :selected').val();
            $.ajax({
                url: '/quotation/ajax/mfglist/',
                method: "GET",
                data: {
                    cate_id: cate_id,
                },
                success: function (res){
                    $('#id_mfg').empty();
                    $("#id_mfg").append($("<option value>").text("---------"));
                    for (const i in res.mfgs){
                        let option = $("<option>").val(res.mfgs[i].id).text(res.mfgs[i].id_name);
                        $("#id_mfg").append(option);
                    }
                },
            });
        });
    });
  </script>
{% endblock %}

templates/quotation/item/detail.html
{% extends 'frame/base.html' %}

{% block title %}{{ item.name }} - 詳細資料{% endblock %}
{% block css %}
  <link href="/static/custom/page.css" rel="stylesheet">
{% endblock %}
{% block scripts %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
  <script>
    /* list.js config*/
    var options = {
      valueNames: [ 'inqry', 'comp', 'price_origin', 'price', 'date'],
      page: 10,
      pagination: [{
          name: "pagination",
          paginationClass: "pagination",
          innerWindow: 1,
          outerWindow: 1,
      }],
    };
    var userList = new List('table', options);
  </script>
  {{ quota_data|json_script:"quota_data" }}
  <script>
    const quota_data = JSON.parse(document.getElementById('quota_data').textContent);
    TESTER = document.getElementById('tester');
    var data = [
        {
            type: 'scatter',
            name: "價格",
            x: quota_data.time,
            y: quota_data.price,
            line: {color: '#17BECF'}
        }
    ];
    var layout = {
      title: '報價趨勢圖',
      xaxis: {
        title: {
          text: "日期",
          font: {
            family: 'Courier New, monospace',
            size: 18,
            color: '#7F7F7F'
          }
        },
        autorange: true,
        type: 'date',
        rangeselector: {buttons: [
          {
            count: 7,
            label: '7d',
            step: 'day',
            stepmode: 'backward'
          },
          {
            count: 1,
            label: '1m',
            step: 'month',
            stepmode: 'backward'
          },
          {step: 'all'}
        ]},
      },
      yaxis: {
        autorange: true,
        type: 'linear',
        title: {
          text: "價格(新台幣)",
          font: {
            family: 'Courier New, monospace',
            size: 18,
            color: '#7F7F7F'
          }
        },
      }
    };
    Plotly.newPlot( TESTER, data, layout);
  </script>
{% endblock %}
{% block content %}
  <section id="basic" class="py-3">
    <div class="container py-3">
      <h1 class="my-3">{{ item.sn }}_{{ item.name }} - 詳細資料</h1>
      <div class="text-right"><small>新增日期：{{ item.addtime|date:"Y-m-d h:i:s a" }} by {{ item.author }}</small></div>
      <div class="text-right"><small>上次修改日期：{{ item.history.latest.history_date|date:"Y-m-d h:i:s a" }} by {{ item.history.latest.history_user }}</small></div>
      <!--按鈕區域-->
      <a role="button" class="btn btn-primary" href="{% url 'Item_Lsit' %}">回品項列表</a>
      <a role="button" class="btn btn-secondary" href="{% url 'Item_Hist_Exprt' item.id %}">匯出歷史報價</a>
      <a role="button" class="btn btn-danger" href="{% url 'Item_Update' item.id %}">編輯</a>

      <!-- 觸發永久刪除視窗 -->
      {% if item.itemquota.count == 0 %}
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#permDelModal">
          永久刪除
        </button>
      {% endif %}

      <!-- 彈出永久刪除視窗 -->
      <div class="modal fade" id="permDelModal" tabindex="-1" role="dialog" aria-labelledby="permDelModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="permDelModalLabel">確認永久刪除？</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>是否永久刪除 {{ item }} 資料?</p>
              <p>(此刪除將無法復原，將從資料庫永久刪除，只有在沒有關聯任何資料時才會刪除。)</p>

            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
              <a href="{% url 'Item_PermDel' item.id %}"><button type="button" class="btn btn-danger">確定永久刪除</button></a>
            </div>
          </div>
        </div>
      </div>

      <!--詳細資料區-->
      <div class="row">
        <div class="col-md-6 my-3">
          <h6>料號：</h6>
          <h5 class="font-weight-bold">{{ item.sn }}</h5>
        </div>
        <div class="col-md-6 my-3">
          <h6>品項名稱：</h6>
          <h5 class="font-weight-bold">{{ item.name }}</h5>
        </div>
        <div class="col-md-3 my-3">
          <h6>類別：</h6>
          <h5 class="font-weight-bold">{{ item.cate }}</h5>
        </div>
        <div class="col-md-3 my-3">
          <h6>製造商：</h6>
          <h5 class="font-weight-bold">{{ item.mfg }}</h5>
        </div>
        <div class="col-md-4 my-3">
          <h6>規格：</h6>
          <h5 class="font-weight-bold">{{ item.specmain }}</h5>
        </div>
        <div class="col-md-2 my-3">
          <h6>詢價狀態：</h6>
          <h5 class="font-weight-bold">
            {% if item.is_inquiry %}
              詢價中
            {% else %}
              不詢價
            {% endif %}
          </h5>
        </div>
        <div class="col-12 my-3">
          <h6>備註：</h6>
          <h5 class="font-weight-bold">{{ item.remark }}</h5>
        </div>
      </div>
    </div>
  </section>
  <section id="ploy">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="align-content-center" id="tester" style="width:100%;height:400px;"></div>
        </div>
      </div>
    </div>
  </section>
  <section id="quotas">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h5 class="font-weight-bold">歷史報價</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-12" id="table">
          <table class="table table-hover">
              <thead>
                <tr class="text-center">
                  <th scope="col" class="sort" data-sort="inqry">報價單</th>
                  <th scope="col" class="sort" data-sort="comp">廠商</th>
                  <th scope="col" class="sort text-right" data-sort="price_origin">報價</th>
                  <th scope="col" class="text-right">幣別(匯率)</th>
                  <th scope="col" class="sort text-right" data-sort="price">報價(新台幣)</th>
                  <th scope="col" class="sort" data-sort="date">時間</th>
                </tr>
              </thead>
              <tbody class="list">
                {% for quota in quotas %}
                  <tr class="text-center">
                    <td class="inqry">
                      <a href="{% url 'Inquiry_Detail' quota.inquirysn.id %}">{{ quota.inquirysn.sn }}</a>
                    </td>
                    <td class="comp">{{ quota.inquirysn.company.shortname }}</td>
                    <td class="price_origin text-right fit">{{ quota.price|floatformat:"2g" }}</td>
                    <td class="text-right fit">
                      {% if quota.price %}
                        {{ quota.crnt.name }}({{ quota.xchgrt|floatformat:"2g" }})
                      {% endif %}
                    </td>
                    <td class="price text-right fit">{{ quota.ntd_price|floatformat:"2g" }}</td>
                    <td class="date">{{ quota.qdate|date:"Y-m-d" }}</td>
                  </tr>
                {% empty %}
                  <tr>
                    <td colspan="6" class="text-center"> Empty </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/quotation/item/list.html
{% extends 'frame/base.html' %}

{% block title %}品項列表 - 寶晶供應鏈管理系統{% endblock %}
{% block css %}
  <link href="/static/custom/page.css" rel="stylesheet">
{% endblock %}
{% block scripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
    <script>
      var options = {
        valueNames: [ 'sn', 'fullname', 'category', 'spec', 'qdate', 'manufacturer'],
        page: 10,
        pagination: [{
            name: "pagination",
            paginationClass: "pagination",
            innerWindow: 1,
            outerWindow: 1,
        }],
      };

      /*table = id of the div */
      var userList = new List('item-list', options);
    </script>
{% endblock %}
{% block content %}
  <section id="doclist" class="py-3">
    <div class="container py-3">
      <h1 class="my-3">品項一覽</h1>
      <div class="row">
        <div class="col-12 my-3">
          <a role="button" class="btn btn-primary" href="{% url 'Item_add' %}">新增</a>
        </div>
        <div class="col-12 my-3">
          <a role="button" class="btn btn-primary" href="{% url 'Cate_Lsit' %}">類別一覽</a>
          <a role="button" class="btn btn-primary" href="{% url 'MFG_Lsit' %}">廠商一覽</a>
        </div>
        <div class="col-12">
          <div class="table-responsive" id="item-list">
            <div class="form-row">
              <div class="col-5">
                <div class="form-group row">
                  <label for="id_cate_id" class="col-3 col-form-label">類別篩選</label>
                  <div class="col-6">
                    <select name="cate_id" class="form-control" id="id_cate_id">
                      <option value="" selected>全部</option>
                      {% for cate in cates_list %}
                        <option value="{{ cate.id }}">{{ cate.name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-3">
                    <input id="catefilter" class="btn btn-primary ml-3" type="button" value="篩選">
                  </div>
                </div>
              </div>
              <div class="col-1"></div>
              <div class="col-6">
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">搜尋...</span>
                  </div>
                  <input type="text" class="search form-control" placeholder="輸入關鍵字" aria-label="Username" aria-describedby="basic-addon1">
                </div>
              </div>
            </div>

            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col" class="sort" data-sort="sn">料號</th>
                  <th scope="col" class="sort fit" data-sort="fullname">品名</th>
                  <th scope="col" class="sort text-center" data-sort="category">類別</th>
                  <th scope="col" class="sort text-center" data-sort="manufacturer">廠商</th>
                  <th scope="col" class="sort text-center" data-sort="spec">規格</th>
                  <th scope="col" class="fit sort text-center" data-sort="qdate">最新報價日</th>
                  <th scope="col" class="text-center fit">詢價中</th>
                </tr>
              </thead>
              <tbody class="list">
                {% for item in items %}
                <tr>
                  <td class="sn"><a href="{% url 'Item_Detail' item.id %}">{{ item.sn }}</a></td>
                  <td class="fullname">{{ item.name }}</td>
                  <td class="category text-center">{{ item.cate }}</td>
                  <td class="manufacturer text-center">{{ item.mfg }}</td>
                  <td class="spec text-center">{{ item.specmain }}</td>
                  <td class="qdate text-center">{% if item.last_quotatime %}{{ item.last_quotatime }}{% endif %}</td>
                  <td class="text-center">{% if item.is_inquiry %}是{% else %}否{% endif %}</td>
                </tr>
                {% empty %}
                  <tr>
                    <td colspan="7" class="text-center"> 目前尚無任何品項。 </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <nav aria-label="Page navigation">
              <ul class="pagination"></ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script>
    $(document).ready(function () {
        let url = $(location).attr('search');
        let get_cate_id = url.split("=")[1]
        $('#id_cate_id').val(get_cate_id).change();
    });
    $(document).on('click', '#catefilter', function () {
        let cate_id = $('#id_cate_id').val();
        window.location.href= '/quotation/item/?cate_id=' + cate_id;
    });
  </script>
{% endblock %}

templates/quotation/item/update.html
{% extends 'frame/base.html' %}

{% block title %}編輯 {{ item.sn }} 資料 - 寶晶供應鏈管理系統{% endblock %}
{% block content %}
  <section id="doclist" class="py-3">
    <div class="container py-3">
      <h1 class="my-3">編輯 {{ item.sn }} - {{ item.name }} 資料</h1>
      <div class="row">
        <div class="col-12">
          <div id="msg" class="text-danger"></div>
          <div class="text-danger">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                  </div>
                {% endfor %}
              {% endfor %}
            {% endif %}
          </div>
        </div>
        <div class="col-12">
          <form method="POST" class="needs-validation" onsubmit="" novalidate>
            <div class="form-row">
              {% csrf_token %}
              <div class="col-12 my-2">{{ form.non_field_errors }}</div>
              <div class="col-12">
                <div class="row">
                  <div class="col-12 col-md-3">
                    <div class="form-group">
                      <label for="id_sn">料號：</label>
                      <div id="id_sn" class="h4">{{ item.sn }}</div>
                    </div>
                  </div>
                  <div class="col-12 col-md-3">
                    <div class="form-group">
                      <label for="id_cate">類別：</label>
                      <div id="id_cate" class="h4">{{ item.cate }}</div>
                    </div>
                  </div>
                  <div class="col-12 col-md-3">
                    <div class="form-group">
                      <label for="id_mfg">廠商：</label>
                      <div id="id_mfg" class="h4">{{ item.mfg }}</div>
                    </div>
                  </div>
                  <div class="col-6 col-md-3">
                    <div class="form-group">
                      <label for="id_spec">規格：</label>
                      <div id="id_spec" class="h4">{{ item.specmain }}</div>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <label for="id_{{ form.name.name }}">品項名稱：</label>
                      {{ form.name }}
                      <small id="nameHelpBlock" class="form-text text-muted">
                        輸入品項名稱。
                      </small>
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-group">
                      <label for="id_{{ form.remark.name }}">備註：</label>
                      {{ form.remark }}
                    </div>
                  </div>
                  <div class="col-12 mb-3">
                    <div class="custom-control custom-switch">
                      {{ form.is_inquiry }}
                      <label class="custom-control-label" for="id_{{ form.is_inquiry.name }}">是否詢價？</label>
                    </div>
                  </div>
                </div>
              </div>
              <input type="hidden" name="author" value="{{ request.user.id }}">
              <div class="col-12">
                <a role="button" class="btn btn-danger" href="../">取消</a>
                <button type="submit" class="btn btn-primary" id="submit">送出</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}
{% block scripts %}
  <script>
    $(document).ready(function (){
        $(document).on('click', '#submit', function (){
          $('input, select').prop('disabled', false);
        });
    });
  </script>
{% endblock %}